### ISSUE TITLE
Siad has exited unexpectedly. Error Log

### ISSUE THREAD

**Issue by PierriGi** [NebulousLabs/docker-sia#58]
Sia Daemon v1.3.7
Git Revision 126260536
Loading...
(0/6) Loading siad...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
(4/6) Loading wallet...
(5/6) Loading host...
(6/6) Loading renter...
Finished loading in 10.0945764 seconds

**Comment by ro-tex** [comment]
1. This is a pretty ancient version of the daemon that's working on the old fork of the blockchain. My first recommendation would be to immediately upgrade to a more recent version that's operating on the current fork, i.e. 1.5.5 or 1.5.6.
2. The provided log only shows the standard starting sequence of `siad`. The error that caused the unexpected exit is most probably in `renter.log`.

I'm closing this issue because it's not relevant to the current state of `siad` or the docker image itself. Please upgrade to a recent version and see how that works for you. If you run into issues again, please open a new issue.

PS: For more info about the fork, please refer to https://support.sia.tech/forks/navigating-the-2021-sia-hardfork
